title: In the Midst
email: info.prelude203@simplelogin.fr
description: >-
  Personal site and blog by Jonathan Bateman.
baseurl: # <--- REPLACE THIS with your GitHub Repo name (e.g., /my-website)
url: "https://Trust-Worthy.github.io" # <--- Replace with your GitHub URL
github_username: Trust-Worthy

plugins:
  - jekyll-feed